find_path(GTKGLEXTMM_INCLUDE_DIR NAMES gtkglmm.h
    PATHS
    /usr/include/gtkglextmm-1.2
    ${INCLUDE_INSTALL_DIR}
    ${GTKGLEXTMM_INCLUDE_PATH}
)

find_path(GTKGLEXTMM_X64_INCLUDE_DIR NAMES gdkglextmm-config.h
    PATHS
    /usr/lib/x86_64-linux-gnu/gtkglextmm-1.2/include
)

find_path(GTKGLEXTMM_GTKGLEXT_INCLUDE_DIR NAMES gdkglext-config.h
    PATHS
    /usr/lib/gtkglext-1.0/include
)

find_path(GTKGLEXTMM_GTKGLEXT_INCLUDE_DIR2 NAMES gdk/gdkgltypes.h
    PATHS
    /usr/include/gtkglext-1.0
)

find_library(GTKGLEXTMM_GTK_LIBRARY gtkglextmm-x11-1.2)
find_library(GTKGLEXTMM_GDK_LIBRARY gdkglextmm-x11-1.2)

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GTKGLEXTMM DEFAULT_MSG
    GTKGLEXTMM_INCLUDE_DIR
    GTKGLEXTMM_X64_INCLUDE_DIR
    GTKGLEXTMM_GTKGLEXT_INCLUDE_DIR
    GTKGLEXTMM_GTKGLEXT_INCLUDE_DIR2
    GTKGLEXTMM_GTK_LIBRARY
    GTKGLEXTMM_GDK_LIBRARY
)
if (GTKGLEXTMM_FOUND)
    set(GTKGLEXTMM_INCLUDE_DIRS ${GTKGLEXTMM_INCLUDE_DIR};${GTKGLEXTMM_X64_INCLUDE_DIR};${GTKGLEXTMM_GTKGLEXT_INCLUDE_DIR};${GTKGLEXTMM_GTKGLEXT_INCLUDE_DIR2})
    set(GTKGLEXTMM_LIBRARIES ${GTKGLEXTMM_GTK_LIBRARY};${GTKGLEXTMM_GDK_LIBRARY})
    message(STATUS "include dirs: ${GTKGLEXTMM_INCLUDE_DIRS}" )
    message(STATUS "libraries: ${GTKGLEXTMM_LIBRARIES}" )
endif( )

mark_as_advanced(GTKGLEXTMM_INCLUDE_DIR)
